Update patch set 6
Patch Set 6:

(3 comments)

Tried compiling this for M3K native and I got link errors (I should've tried this before obviously)

calculator.c:(.text.twoOperands+0x2d4): undefined reference to `snprintf'
calculator.c:(.text.twoOperands+0x2e0): undefined reference to `strtod'
calculator.c:(.text.twoOperands+0x310): undefined reference to `snprintf'
calculator.c:(.text.twoOperands+0x31c): undefined reference to `strtod'
calculator.c:(.text.twoOperands+0x34c): undefined reference to `atoi'

snprintf and atoi are no problem just change them to rb->snprintf and rb->atoi.

strtod is more annoying, you will need to copy one of the strtod implementations from another plugin and put it here. (I didn't review them at all, you should also make sure they're going to be accurate enough for you here.)

I will try this on my end and look into any printf related issues as I suspect the defines will need to be updated. Unless you're planning on #ifdef'ing this whole chunk out on native targets, in which case the strtod/printf issues are moot.

Patch-set: 6